// Studio UX tokens @ v1.1.15 — GERADO de packages/tokens/tokens.css. NÃO editar (regenere: npm run export:tokens).
import 'package:flutter/material.dart';

abstract class SuTokensLight {
  static const Color action = Color(0xFF4F46E5);
  static const Color actionActive = Color(0xFF3730A3);
  static const Color actionHover = Color(0xFF4338CA);
  static const Color actionTint = Color(0xFFEEEFFE);
  static const Color borderDefault = Color(0xFFDDE1E8);
  static const Color borderFocus = Color(0xFF4F46E5);
  static const Color borderStrong = Color(0xFFC4CAD4);
  static const Color borderSubtle = Color(0xFFEDEFF3);
  static const double bpLg = 1024.0;
  static const double bpMd = 768.0;
  static const double bpSm = 480.0;
  static const double bpXl = 1280.0;
  static const Color danger = Color(0xFFDC2626);
  static const Color dangerBg = Color(0xFFFCE9E9);
  static const Color dangerFg = Color(0xFFD12424);
  static const int durationBase = 200; // ms
  static const int durationFast = 120; // ms
  static const int durationSlow = 320; // ms
  static const String easeEntrance = "cubic-bezier(0, 0, 0.2, 1)";
  static const String easeExit = "cubic-bezier(0.4, 0, 1, 1)";
  static const String easeStandard = "cubic-bezier(0.2, 0, 0, 1)";
  static const String elevationModal = "0 16px 40px rgba(23,26,31,.18)";
  static const String elevationOverlay = "0 6px 16px rgba(23,26,31,.10), 0 2px 5px rgba(23,26,31,.06)";
  static const String elevationRaised = "0 1px 2px rgba(23,26,31,.06), 0 1px 3px rgba(23,26,31,.05)";
  static const String fontMono = "\"JetBrains Mono\", ui-monospace, SFMono-Regular, Menlo, monospace";
  static const String fontUi = "\"Inter\", system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif";
  static const double fsBody = 15.0;
  static const double fsBodySm = 13.0;
  static const double fsCaption = 12.0;
  static const double fsDisplay = 32.0;
  static const double fsH1 = 24.0;
  static const double fsH2 = 20.0;
  static const double fsH3 = 16.0;
  static const double fsLabel = 13.0;
  static const int fwMedium = 500;
  static const int fwRegular = 400;
  static const int fwSemibold = 600;
  static const double iconLg = 24.0;
  static const double iconMd = 20.0;
  static const double iconSm = 16.0;
  static const Color infoBg = Color(0xFFE8F0FE);
  static const Color infoFg = Color(0xFF2563EB);
  static const double opacityDisabled = 0.55;
  static const double opacityMuted = 0.7;
  static const double opacityOverlay = 0.44;
  static const double radiusFull = 9999.0;
  static const double radiusLg = 12.0;
  static const double radiusMd = 8.0;
  static const double radiusSm = 6.0;
  static const double radiusXl = 16.0;
  static const double space1 = 4.0;
  static const double space12 = 48.0;
  static const double space16 = 64.0;
  static const double space2 = 8.0;
  static const double space24 = 96.0;
  static const double space3 = 12.0;
  static const double space4 = 16.0;
  static const double space5 = 20.0;
  static const double space6 = 24.0;
  static const double space8 = 32.0;
  static const Color successBg = Color(0xFFE6F4EE);
  static const Color successFg = Color(0xFF047857);
  static const Color surfaceBase = Color(0xFFF7F8FA);
  static const Color surfaceOverlay = Color(0xFFFFFFFF);
  static const Color surfaceRaised = Color(0xFFFFFFFF);
  static const Color surfaceSunken = Color(0xFFEDEFF3);
  static const double textBody = 15.0; // line-height 1.5
  static const double textBodySm = 13.0; // line-height 1.5
  static const double textCaption = 12.0; // line-height 1.4
  static const Color textDisabled = Color(0xFFC4CAD4);
  static const double textDisplay = 32.0; // line-height 1.2
  static const double textH1 = 24.0; // line-height 1.25
  static const double textH2 = 20.0; // line-height 1.3
  static const double textH3 = 16.0; // line-height 1.4
  static const double textLabel = 13.0; // line-height 1.35
  static const Color textMuted = Color(0xFF8E95A1);
  static const Color textOnAction = Color(0xFFFFFFFF);
  static const Color textPrimary = Color(0xFF171A1F);
  static const Color textSecondary = Color(0xFF545B67);
  static const Color warningBg = Color(0xFFFBF0DD);
  static const Color warningFg = Color(0xFFB25209);
  static const int zBase = 0;
  static const int zContent = 1;
  static const int zModal = 1000;
  static const int zOverlay = 900;
  static const int zSticky = 100;
  static const int zToast = 1100;
}

abstract class SuTokensDark {
  static const Color action = Color(0xFF6365F0);
  static const Color actionActive = Color(0xFF4F46E5);
  static const Color actionHover = Color(0xFF7B7DF5);
  static const Color actionTint = Color(0xFF21243A);
  static const Color borderDefault = Color(0xFF2A2E37);
  static const Color borderFocus = Color(0xFF6366F1);
  static const Color borderStrong = Color(0xFF3A3F49);
  static const Color borderSubtle = Color(0xFF23262E);
  static const double bpLg = 1024.0;
  static const double bpMd = 768.0;
  static const double bpSm = 480.0;
  static const double bpXl = 1280.0;
  static const Color danger = Color(0xFFF87171);
  static const Color dangerBg = Color(0xFF3A1A1A);
  static const Color dangerFg = Color(0xFFF87171);
  static const int durationBase = 200; // ms
  static const int durationFast = 120; // ms
  static const int durationSlow = 320; // ms
  static const String easeEntrance = "cubic-bezier(0, 0, 0.2, 1)";
  static const String easeExit = "cubic-bezier(0.4, 0, 1, 1)";
  static const String easeStandard = "cubic-bezier(0.2, 0, 0, 1)";
  static const String elevationModal = "0 18px 44px rgba(0,0,0,.50)";
  static const String elevationOverlay = "0 8px 24px rgba(0,0,0,.40)";
  static const String elevationRaised = "0 1px 2px rgba(0,0,0,.30)";
  static const String fontMono = "\"JetBrains Mono\", ui-monospace, SFMono-Regular, Menlo, monospace";
  static const String fontUi = "\"Inter\", system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif";
  static const double fsBody = 15.0;
  static const double fsBodySm = 13.0;
  static const double fsCaption = 12.0;
  static const double fsDisplay = 32.0;
  static const double fsH1 = 24.0;
  static const double fsH2 = 20.0;
  static const double fsH3 = 16.0;
  static const double fsLabel = 13.0;
  static const int fwMedium = 500;
  static const int fwRegular = 400;
  static const int fwSemibold = 600;
  static const double iconLg = 24.0;
  static const double iconMd = 20.0;
  static const double iconSm = 16.0;
  static const Color infoBg = Color(0xFF16233F);
  static const Color infoFg = Color(0xFF60A5FA);
  static const double opacityDisabled = 0.55;
  static const double opacityMuted = 0.7;
  static const double opacityOverlay = 0.44;
  static const double radiusFull = 9999.0;
  static const double radiusLg = 12.0;
  static const double radiusMd = 8.0;
  static const double radiusSm = 6.0;
  static const double radiusXl = 16.0;
  static const double space1 = 4.0;
  static const double space12 = 48.0;
  static const double space16 = 64.0;
  static const double space2 = 8.0;
  static const double space24 = 96.0;
  static const double space3 = 12.0;
  static const double space4 = 16.0;
  static const double space5 = 20.0;
  static const double space6 = 24.0;
  static const double space8 = 32.0;
  static const Color successBg = Color(0xFF123028);
  static const Color successFg = Color(0xFF34D399);
  static const Color surfaceBase = Color(0xFF14161B);
  static const Color surfaceOverlay = Color(0xFF24272F);
  static const Color surfaceRaised = Color(0xFF1C1F26);
  static const Color surfaceSunken = Color(0xFF101216);
  static const double textBody = 15.0; // line-height 1.5
  static const double textBodySm = 13.0; // line-height 1.5
  static const double textCaption = 12.0; // line-height 1.4
  static const Color textDisabled = Color(0xFF4A5059);
  static const double textDisplay = 32.0; // line-height 1.2
  static const double textH1 = 24.0; // line-height 1.25
  static const double textH2 = 20.0; // line-height 1.3
  static const double textH3 = 16.0; // line-height 1.4
  static const double textLabel = 13.0; // line-height 1.35
  static const Color textMuted = Color(0xFF6E7683);
  static const Color textOnAction = Color(0xFFFFFFFF);
  static const Color textPrimary = Color(0xFFF2F4F7);
  static const Color textSecondary = Color(0xFFA6ADBA);
  static const Color warningBg = Color(0xFF3A2A12);
  static const Color warningFg = Color(0xFFE0A82E);
  static const int zBase = 0;
  static const int zContent = 1;
  static const int zModal = 1000;
  static const int zOverlay = 900;
  static const int zSticky = 100;
  static const int zToast = 1100;
}
