// Studio UX tokens @ v1.1.9 — GERADO de packages/tokens/tokens.css. NÃO editar (regenere: npm run export:tokens).
import SwiftUI

extension Color {
    init(su hex: UInt32) {
        self.init(.sRGB, red: Double((hex >> 16) & 0xFF) / 255, green: Double((hex >> 8) & 0xFF) / 255, blue: Double(hex & 0xFF) / 255, opacity: 1)
    }
}

enum SuTokensLight {
    static let action = Color(su: 0x4F46E5)
    static let actionActive = Color(su: 0x3730A3)
    static let actionHover = Color(su: 0x4338CA)
    static let actionTint = Color(su: 0xEEEFFE)
    static let borderDefault = Color(su: 0xDDE1E8)
    static let borderFocus = Color(su: 0x4F46E5)
    static let borderStrong = Color(su: 0xC4CAD4)
    static let borderSubtle = Color(su: 0xEDEFF3)
    static let bpLg: CGFloat = 1024
    static let bpMd: CGFloat = 768
    static let bpSm: CGFloat = 480
    static let bpXl: CGFloat = 1280
    static let danger = Color(su: 0xDC2626)
    static let dangerBg = Color(su: 0xFCE9E9)
    static let dangerFg = Color(su: 0xD12424)
    static let durationBase = 200 // ms
    static let durationFast = 120 // ms
    static let durationSlow = 320 // ms
    static let easeEntrance = "cubic-bezier(0, 0, 0.2, 1)"
    static let easeExit = "cubic-bezier(0.4, 0, 1, 1)"
    static let easeStandard = "cubic-bezier(0.2, 0, 0, 1)"
    static let elevationModal = "0 16px 40px rgba(23,26,31,.18)"
    static let elevationOverlay = "0 6px 16px rgba(23,26,31,.10), 0 2px 5px rgba(23,26,31,.06)"
    static let elevationRaised = "0 1px 2px rgba(23,26,31,.06), 0 1px 3px rgba(23,26,31,.05)"
    static let fontMono = "\"JetBrains Mono\", ui-monospace, SFMono-Regular, Menlo, monospace"
    static let fontUi = "\"Inter\", system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif"
    static let fwMedium = 500
    static let fwRegular = 400
    static let fwSemibold = 600
    static let iconLg: CGFloat = 24
    static let iconMd: CGFloat = 20
    static let iconSm: CGFloat = 16
    static let infoBg = Color(su: 0xE8F0FE)
    static let infoFg = Color(su: 0x2563EB)
    static let opacityDisabled: Double = 0.55
    static let opacityMuted: Double = 0.7
    static let opacityOverlay: Double = 0.44
    static let radiusFull: CGFloat = 9999
    static let radiusLg: CGFloat = 12
    static let radiusMd: CGFloat = 8
    static let radiusSm: CGFloat = 6
    static let radiusXl: CGFloat = 16
    static let space1: CGFloat = 4
    static let space12: CGFloat = 48
    static let space16: CGFloat = 64
    static let space2: CGFloat = 8
    static let space24: CGFloat = 96
    static let space3: CGFloat = 12
    static let space4: CGFloat = 16
    static let space5: CGFloat = 20
    static let space6: CGFloat = 24
    static let space8: CGFloat = 32
    static let successBg = Color(su: 0xE6F4EE)
    static let successFg = Color(su: 0x047857)
    static let surfaceBase = Color(su: 0xF7F8FA)
    static let surfaceOverlay = Color(su: 0xFFFFFF)
    static let surfaceRaised = Color(su: 0xFFFFFF)
    static let surfaceSunken = Color(su: 0xEDEFF3)
    static let textBody: CGFloat = 15 // line-height 1.5
    static let textBodySm: CGFloat = 13 // line-height 1.5
    static let textCaption: CGFloat = 12 // line-height 1.4
    static let textDisabled = Color(su: 0xC4CAD4)
    static let textDisplay: CGFloat = 32 // line-height 1.2
    static let textH1: CGFloat = 24 // line-height 1.25
    static let textH2: CGFloat = 20 // line-height 1.3
    static let textH3: CGFloat = 16 // line-height 1.4
    static let textLabel: CGFloat = 13 // line-height 1.35
    static let textMuted = Color(su: 0x8E95A1)
    static let textOnAction = Color(su: 0xFFFFFF)
    static let textPrimary = Color(su: 0x171A1F)
    static let textSecondary = Color(su: 0x545B67)
    static let warningBg = Color(su: 0xFBF0DD)
    static let warningFg = Color(su: 0xB25209)
    static let zBase = 0
    static let zContent = 1
    static let zModal = 1000
    static let zOverlay = 900
    static let zSticky = 100
    static let zToast = 1100
}

enum SuTokensDark {
    static let action = Color(su: 0x6365F0)
    static let actionActive = Color(su: 0x4F46E5)
    static let actionHover = Color(su: 0x7B7DF5)
    static let actionTint = Color(su: 0x21243A)
    static let borderDefault = Color(su: 0x2A2E37)
    static let borderFocus = Color(su: 0x6366F1)
    static let borderStrong = Color(su: 0x3A3F49)
    static let borderSubtle = Color(su: 0x23262E)
    static let bpLg: CGFloat = 1024
    static let bpMd: CGFloat = 768
    static let bpSm: CGFloat = 480
    static let bpXl: CGFloat = 1280
    static let danger = Color(su: 0xF87171)
    static let dangerBg = Color(su: 0x3A1A1A)
    static let dangerFg = Color(su: 0xF87171)
    static let durationBase = 200 // ms
    static let durationFast = 120 // ms
    static let durationSlow = 320 // ms
    static let easeEntrance = "cubic-bezier(0, 0, 0.2, 1)"
    static let easeExit = "cubic-bezier(0.4, 0, 1, 1)"
    static let easeStandard = "cubic-bezier(0.2, 0, 0, 1)"
    static let elevationModal = "0 18px 44px rgba(0,0,0,.50)"
    static let elevationOverlay = "0 8px 24px rgba(0,0,0,.40)"
    static let elevationRaised = "0 1px 2px rgba(0,0,0,.30)"
    static let fontMono = "\"JetBrains Mono\", ui-monospace, SFMono-Regular, Menlo, monospace"
    static let fontUi = "\"Inter\", system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif"
    static let fwMedium = 500
    static let fwRegular = 400
    static let fwSemibold = 600
    static let iconLg: CGFloat = 24
    static let iconMd: CGFloat = 20
    static let iconSm: CGFloat = 16
    static let infoBg = Color(su: 0x16233F)
    static let infoFg = Color(su: 0x60A5FA)
    static let opacityDisabled: Double = 0.55
    static let opacityMuted: Double = 0.7
    static let opacityOverlay: Double = 0.44
    static let radiusFull: CGFloat = 9999
    static let radiusLg: CGFloat = 12
    static let radiusMd: CGFloat = 8
    static let radiusSm: CGFloat = 6
    static let radiusXl: CGFloat = 16
    static let space1: CGFloat = 4
    static let space12: CGFloat = 48
    static let space16: CGFloat = 64
    static let space2: CGFloat = 8
    static let space24: CGFloat = 96
    static let space3: CGFloat = 12
    static let space4: CGFloat = 16
    static let space5: CGFloat = 20
    static let space6: CGFloat = 24
    static let space8: CGFloat = 32
    static let successBg = Color(su: 0x123028)
    static let successFg = Color(su: 0x34D399)
    static let surfaceBase = Color(su: 0x14161B)
    static let surfaceOverlay = Color(su: 0x24272F)
    static let surfaceRaised = Color(su: 0x1C1F26)
    static let surfaceSunken = Color(su: 0x101216)
    static let textBody: CGFloat = 15 // line-height 1.5
    static let textBodySm: CGFloat = 13 // line-height 1.5
    static let textCaption: CGFloat = 12 // line-height 1.4
    static let textDisabled = Color(su: 0x4A5059)
    static let textDisplay: CGFloat = 32 // line-height 1.2
    static let textH1: CGFloat = 24 // line-height 1.25
    static let textH2: CGFloat = 20 // line-height 1.3
    static let textH3: CGFloat = 16 // line-height 1.4
    static let textLabel: CGFloat = 13 // line-height 1.35
    static let textMuted = Color(su: 0x6E7683)
    static let textOnAction = Color(su: 0xFFFFFF)
    static let textPrimary = Color(su: 0xF2F4F7)
    static let textSecondary = Color(su: 0xA6ADBA)
    static let warningBg = Color(su: 0x3A2A12)
    static let warningFg = Color(su: 0xE0A82E)
    static let zBase = 0
    static let zContent = 1
    static let zModal = 1000
    static let zOverlay = 900
    static let zSticky = 100
    static let zToast = 1100
}
